"""add_owner_id_indexes

Revision ID: 8e76015a72ca
Revises: dd8b55b98308
Create Date: 2026-07-03 13:59:35.426983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision: str = '8e76015a72ca'
down_revision: Union[str, Sequence[str], None] = 'dd8b55b98308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _existing_indexes(table_name: str) -> set[str]:
    try:
        return {ix["name"] for ix in inspect(op.get_bind()).get_indexes(table_name)}
    except Exception:
        return set()


def create_index_if_not_exists(index_name: str, table_name: str, columns: list, unique: bool = False) -> None:
    if index_name not in _existing_indexes(table_name):
        op.create_index(op.f(index_name), table_name, columns, unique=unique)


def drop_index_if_exists(index_name: str, table_name: str) -> None:
    if index_name in _existing_indexes(table_name):
        op.drop_index(op.f(index_name), table_name=table_name)


def upgrade() -> None:
    """Upgrade schema."""
    # Index creation is safe on all dialects. ALTER COLUMN TYPE is PostgreSQL-only.
    is_sqlite = op.get_bind().dialect.name == 'sqlite'
    # ### commands auto generated by Alembic - please adjust! ###
    create_index_if_not_exists('ix_customers_owner_id', 'customers', ['owner_id'])
    if not is_sqlite:
        op.alter_column('expenses', 'category',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
        op.alter_column('expenses', 'amount',
                   existing_type=sa.REAL(),
                   type_=sa.Float(),
                   existing_nullable=True)
        op.alter_column('expenses', 'description',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
    create_index_if_not_exists('ix_expenses_id', 'expenses', ['id'])
    create_index_if_not_exists('ix_expenses_owner_id', 'expenses', ['owner_id'])
    if not is_sqlite:
        op.alter_column('ingredients', 'id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   autoincrement=True)
        op.alter_column('ingredients', 'name',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
        op.alter_column('ingredients', 'stock',
                   existing_type=sa.REAL(),
                   type_=sa.Float(),
                   existing_nullable=True)
        op.alter_column('ingredients', 'unit',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
        op.alter_column('ingredients', 'price',
                   existing_type=sa.REAL(),
                   type_=sa.Float(),
                   existing_nullable=True)
        op.alter_column('ingredients', 'min_threshold',
                   existing_type=sa.REAL(),
                   type_=sa.Float(),
                   existing_nullable=True)
        op.alter_column('ingredients', 'supplier',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
        op.alter_column('ingredients', 'last_purchase_price',
                   existing_type=sa.REAL(),
                   type_=sa.Float(),
                   existing_nullable=True)
    create_index_if_not_exists('ix_ingredients_id', 'ingredients', ['id'])
    create_index_if_not_exists('ix_ingredients_name', 'ingredients', ['name'])
    create_index_if_not_exists('ix_ingredients_owner_id', 'ingredients', ['owner_id'])
    create_index_if_not_exists('ix_orders_owner_id', 'orders', ['owner_id'])
    create_index_if_not_exists('ix_planner_owner_id', 'planner', ['owner_id'])
    create_index_if_not_exists('ix_products_owner_id', 'products', ['owner_id'])
    create_index_if_not_exists('ix_purchase_orders_owner_id', 'purchase_orders', ['owner_id'])
    if not is_sqlite:
        op.alter_column('recipe_items', 'id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   autoincrement=True)
        op.alter_column('recipe_items', 'product_id',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
        op.alter_column('recipe_items', 'quantity',
                   existing_type=sa.REAL(),
                   type_=sa.Float(),
                   existing_nullable=True)
    create_index_if_not_exists('ix_recipe_items_id', 'recipe_items', ['id'])
    if not is_sqlite:
        op.drop_constraint(None, 'recipe_items', type_='foreignkey')
        op.create_foreign_key(None, 'recipe_items', 'ingredients', ['ingredient_id'], ['id'])
    create_index_if_not_exists('ix_shift_logs_owner_id', 'shift_logs', ['owner_id'])
    create_index_if_not_exists('ix_shift_records_owner_id', 'shift_records', ['owner_id'])
    drop_index_if_exists('ix_suppliers_name', 'suppliers')
    create_index_if_not_exists('ix_suppliers_name', 'suppliers', ['name'])
    create_index_if_not_exists('ix_suppliers_owner_id', 'suppliers', ['owner_id'])
    if not is_sqlite:
        op.create_foreign_key(None, 'system_settings', 'users', ['owner_id'], ['id'])
        op.alter_column('transactions', 'status',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True,
                   existing_server_default=sa.text("'completed'"))
    create_index_if_not_exists('ix_transactions_owner_id', 'transactions', ['owner_id'])
    if not is_sqlite:
        op.alter_column('users', 'id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   autoincrement=True)
        op.alter_column('users', 'username',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
        op.alter_column('users', 'password',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
        op.alter_column('users', 'role',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
    create_index_if_not_exists('ix_users_id', 'users', ['id'])
    create_index_if_not_exists('ix_users_parent_owner_id', 'users', ['parent_owner_id'])
    create_index_if_not_exists('ix_users_username', 'users', ['username'], unique=True)
    create_index_if_not_exists('ix_waste_records_owner_id', 'waste_records', ['owner_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    is_sqlite = op.get_bind().dialect.name == 'sqlite'
    # ### commands auto generated by Alembic - please adjust! ###
    drop_index_if_exists('ix_waste_records_owner_id', 'waste_records')
    drop_index_if_exists('ix_users_username', 'users')
    drop_index_if_exists('ix_users_parent_owner_id', 'users')
    drop_index_if_exists('ix_users_id', 'users')
    drop_index_if_exists('ix_transactions_owner_id', 'transactions')
    if not is_sqlite:
        op.drop_constraint(None, 'system_settings', type_='foreignkey')
    drop_index_if_exists('ix_suppliers_owner_id', 'suppliers')
    drop_index_if_exists('ix_suppliers_name', 'suppliers')
    # Downgrade restores the old unique constraint on suppliers.name
    # by re-creating the index as unique=1 (SQLAlchemy shorthand).
    if 'ix_suppliers_name' in _existing_indexes('suppliers'):
        op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    if 'ix_suppliers_name' not in _existing_indexes('suppliers'):
        op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=1)
    drop_index_if_exists('ix_shift_records_owner_id', 'shift_records')
    drop_index_if_exists('ix_shift_logs_owner_id', 'shift_logs')
    if not is_sqlite:
        op.drop_constraint(None, 'recipe_items', type_='foreignkey')
        op.create_foreign_key(None, 'recipe_items', 'ingredients_old', ['ingredient_id'], ['id'])
    drop_index_if_exists('ix_recipe_items_id', 'recipe_items')
    drop_index_if_exists('ix_purchase_orders_owner_id', 'purchase_orders')
    drop_index_if_exists('ix_products_owner_id', 'products')
    drop_index_if_exists('ix_planner_owner_id', 'planner')
    drop_index_if_exists('ix_orders_owner_id', 'orders')
    drop_index_if_exists('ix_ingredients_owner_id', 'ingredients')
    drop_index_if_exists('ix_ingredients_name', 'ingredients')
    drop_index_if_exists('ix_ingredients_id', 'ingredients')
    drop_index_if_exists('ix_expenses_owner_id', 'expenses')
    drop_index_if_exists('ix_expenses_id', 'expenses')
    drop_index_if_exists('ix_customers_owner_id', 'customers')
    # ### end Alembic commands ###