"""add_owner_id_indexes

Revision ID: 8e76015a72ca
Revises: dd8b55b98308
Create Date: 2026-07-03 13:59:35.426983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e76015a72ca'
down_revision: Union[str, Sequence[str], None] = 'dd8b55b98308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Index creation is safe on all dialects. ALTER COLUMN TYPE is PostgreSQL-only.
    is_sqlite = op.get_bind().dialect.name == 'sqlite'
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_customers_owner_id'), 'customers', ['owner_id'], unique=False)
    if not is_sqlite:
        op.alter_column('expenses', 'category',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
        op.alter_column('expenses', 'amount',
                   existing_type=sa.REAL(),
                   type_=sa.Float(),
                   existing_nullable=True)
        op.alter_column('expenses', 'description',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index(op.f('ix_expenses_owner_id'), 'expenses', ['owner_id'], unique=False)
    if not is_sqlite:
        op.alter_column('ingredients', 'id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   autoincrement=True)
        op.alter_column('ingredients', 'name',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
        op.alter_column('ingredients', 'stock',
                   existing_type=sa.REAL(),
                   type_=sa.Float(),
                   existing_nullable=True)
        op.alter_column('ingredients', 'unit',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
        op.alter_column('ingredients', 'price',
                   existing_type=sa.REAL(),
                   type_=sa.Float(),
                   existing_nullable=True)
        op.alter_column('ingredients', 'min_threshold',
                   existing_type=sa.REAL(),
                   type_=sa.Float(),
                   existing_nullable=True)
        op.alter_column('ingredients', 'supplier',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
        op.alter_column('ingredients', 'last_purchase_price',
                   existing_type=sa.REAL(),
                   type_=sa.Float(),
                   existing_nullable=True)
    op.create_index(op.f('ix_ingredients_id'), 'ingredients', ['id'], unique=False)
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=False)
    op.create_index(op.f('ix_ingredients_owner_id'), 'ingredients', ['owner_id'], unique=False)
    op.create_index(op.f('ix_orders_owner_id'), 'orders', ['owner_id'], unique=False)
    op.create_index(op.f('ix_planner_owner_id'), 'planner', ['owner_id'], unique=False)
    op.create_index(op.f('ix_products_owner_id'), 'products', ['owner_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_owner_id'), 'purchase_orders', ['owner_id'], unique=False)
    if not is_sqlite:
        op.alter_column('recipe_items', 'id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   autoincrement=True)
        op.alter_column('recipe_items', 'product_id',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
        op.alter_column('recipe_items', 'quantity',
                   existing_type=sa.REAL(),
                   type_=sa.Float(),
                   existing_nullable=True)
    op.create_index(op.f('ix_recipe_items_id'), 'recipe_items', ['id'], unique=False)
    if not is_sqlite:
        op.drop_constraint(None, 'recipe_items', type_='foreignkey')
        op.create_foreign_key(None, 'recipe_items', 'ingredients', ['ingredient_id'], ['id'])
    op.create_index(op.f('ix_shift_logs_owner_id'), 'shift_logs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_shift_records_owner_id'), 'shift_records', ['owner_id'], unique=False)
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_suppliers_owner_id'), 'suppliers', ['owner_id'], unique=False)
    if not is_sqlite:
        op.create_foreign_key(None, 'system_settings', 'users', ['owner_id'], ['id'])
        op.alter_column('transactions', 'status',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True,
                   existing_server_default=sa.text("'completed'"))
    op.create_index(op.f('ix_transactions_owner_id'), 'transactions', ['owner_id'], unique=False)
    if not is_sqlite:
        op.alter_column('users', 'id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   autoincrement=True)
        op.alter_column('users', 'username',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
        op.alter_column('users', 'password',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
        op.alter_column('users', 'role',
                   existing_type=sa.TEXT(),
                   type_=sa.String(),
                   existing_nullable=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_parent_owner_id'), 'users', ['parent_owner_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_waste_records_owner_id'), 'waste_records', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    is_sqlite = op.get_bind().dialect.name == 'sqlite'
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waste_records_owner_id'), table_name='waste_records')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_parent_owner_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_transactions_owner_id'), table_name='transactions')
    if not is_sqlite:
        op.drop_constraint(None, 'system_settings', type_='foreignkey')
    op.drop_index(op.f('ix_suppliers_owner_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=1)
    op.drop_index(op.f('ix_shift_records_owner_id'), table_name='shift_records')
    op.drop_index(op.f('ix_shift_logs_owner_id'), table_name='shift_logs')
    if not is_sqlite:
        op.drop_constraint(None, 'recipe_items', type_='foreignkey')
        op.create_foreign_key(None, 'recipe_items', 'ingredients_old', ['ingredient_id'], ['id'])
    op.drop_index(op.f('ix_recipe_items_id'), table_name='recipe_items')
    op.drop_index(op.f('ix_purchase_orders_owner_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_products_owner_id'), table_name='products')
    op.drop_index(op.f('ix_planner_owner_id'), table_name='planner')
    op.drop_index(op.f('ix_orders_owner_id'), table_name='orders')
    op.drop_index(op.f('ix_ingredients_owner_id'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_id'), table_name='ingredients')
    op.drop_index(op.f('ix_expenses_owner_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_index(op.f('ix_customers_owner_id'), table_name='customers')
    # ### end Alembic commands ###
