"""reconcile remaining model vs migration drift found by test_migrations

Revision ID: 23625127fff3
Revises: b7eb10446c94
Create Date: 2026-07-16 01:13:24.169669

Context
-------
Generated by `alembic revision --autogenerate` after running the new
`tests/test_migrations.py` drift check, which compares a fully-migrated
database against current `models.py`. It found gaps beyond the two
already known and fixed by the prior two migrations:

  * `financial_events` (models.py's `FinancialEvent`) had no migration
    creating it at all. On the old create_all()-based bootstrap path this
    was invisible -- create_all() always creates missing tables from
    current models regardless of migration history -- but a pure
    Alembic-only chain would never have created it.
  * `custom_orders.owner_id` was created NOT NULL by migration 0017, but
    the model never declared it that way. Reconciled by matching the
    model (loosening the constraint -- safe, non-breaking direction).
  * A handful of indexes on `custom_orders`, `expense_payments`,
    `orders`, `planner`, `products`, and `purchase_invoices` were either
    missing or stale relative to the current models.

Every operation below is guarded so this migration is a safe no-op on a
database where create_all() already independently produced the correct
end state (e.g. an adopted bootstrap database), and does real work on a
database that only ever goes through this migration chain.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23625127fff3'
down_revision: Union[str, Sequence[str], None] = 'b7eb10446c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _inspector():
    bind = op.get_bind()
    return sa.inspect(bind)


def _table_exists(table_name: str) -> bool:
    return table_name in _inspector().get_table_names()


def _index_names(table_name: str) -> set:
    return {ix["name"] for ix in _inspector().get_indexes(table_name)}


def _is_nullable(table_name: str, column_name: str) -> bool:
    for col in _inspector().get_columns(table_name):
        if col["name"] == column_name:
            return bool(col["nullable"])
    raise LookupError(f"{table_name}.{column_name} not found")


def upgrade() -> None:
    """Upgrade schema."""
    if not _table_exists("financial_events"):
        op.create_table('financial_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=True),
        sa.Column('event_type', sa.String(), nullable=False),
        sa.Column('event_subtype', sa.String(), nullable=True),
        sa.Column('amount_ht', sa.Float(), nullable=True),
        sa.Column('tva_rate', sa.Float(), nullable=True),
        sa.Column('tva_amount', sa.Float(), nullable=True),
        sa.Column('amount_ttc', sa.Float(), nullable=True),
        sa.Column('source_type', sa.String(), nullable=True),
        sa.Column('source_id', sa.String(), nullable=True),
        sa.Column('reference_number', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('customer_supplier_id', sa.Integer(), nullable=True),
        sa.Column('item_type', sa.String(), nullable=True),
        sa.Column('item_id', sa.String(), nullable=True),
        sa.Column('item_name_snapshot', sa.String(), nullable=True),
        sa.Column('quantity', sa.Float(), nullable=True),
        sa.Column('unit', sa.String(), nullable=True),
        sa.Column('unit_cost', sa.Float(), nullable=True),
        sa.Column('event_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('created_by_user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['customer_supplier_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('financial_events', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_financial_events_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_financial_events_customer_supplier_id'), ['customer_supplier_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_financial_events_event_at'), ['event_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_financial_events_event_subtype'), ['event_subtype'], unique=False)
            batch_op.create_index(batch_op.f('ix_financial_events_event_type'), ['event_type'], unique=False)
            batch_op.create_index(batch_op.f('ix_financial_events_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_financial_events_item_id'), ['item_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_financial_events_item_type'), ['item_type'], unique=False)
            batch_op.create_index('ix_financial_events_owner_event_at', ['owner_id', 'event_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_financial_events_owner_id'), ['owner_id'], unique=False)
            batch_op.create_index('ix_financial_events_owner_type', ['owner_id', 'event_type'], unique=False)
            batch_op.create_index(batch_op.f('ix_financial_events_reference_number'), ['reference_number'], unique=False)
            batch_op.create_index('ix_financial_events_source', ['source_type', 'source_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_financial_events_source_id'), ['source_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_financial_events_source_type'), ['source_type'], unique=False)

    if _table_exists("custom_orders"):
        co_indexes = _index_names("custom_orders")
        with op.batch_alter_table('custom_orders', schema=None) as batch_op:
            if not _is_nullable("custom_orders", "owner_id"):
                batch_op.alter_column('owner_id', existing_type=sa.INTEGER(), nullable=True)
            if 'ix_custom_orders_payment_status' in co_indexes:
                batch_op.drop_index(batch_op.f('ix_custom_orders_payment_status'))
            if 'ix_custom_orders_owner_status' not in co_indexes:
                batch_op.create_index('ix_custom_orders_owner_status', ['owner_id', 'status'], unique=False)

    if _table_exists("expense_payments") and 'ix_expense_payments_id' not in _index_names("expense_payments"):
        with op.batch_alter_table('expense_payments', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_expense_payments_id'), ['id'], unique=False)

    if _table_exists("orders") and 'ix_orders_id' not in _index_names("orders"):
        with op.batch_alter_table('orders', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_orders_id'), ['id'], unique=False)

    if _table_exists("planner") and 'ix_planner_id' not in _index_names("planner"):
        with op.batch_alter_table('planner', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_planner_id'), ['id'], unique=False)

    if _table_exists("products"):
        prod_indexes = _index_names("products")
        with op.batch_alter_table('products', schema=None) as batch_op:
            if 'ix_products_id' not in prod_indexes:
                batch_op.create_index(batch_op.f('ix_products_id'), ['id'], unique=False)
            if 'ix_products_name' not in prod_indexes:
                batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)

    if _table_exists("purchase_invoices") and 'ix_purchase_invoices_owner_number' in _index_names("purchase_invoices"):
        with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_purchase_invoices_owner_number'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_invoices_owner_number'), ['owner_id', 'invoice_number'], unique=1)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_id'))

    with op.batch_alter_table('planner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planner_id'))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_id'))

    with op.batch_alter_table('expense_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_payments_id'))

    with op.batch_alter_table('custom_orders', schema=None) as batch_op:
        batch_op.drop_index('ix_custom_orders_owner_status')
        batch_op.create_index(batch_op.f('ix_custom_orders_payment_status'), ['payment_status'], unique=False)
        batch_op.alter_column('owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('financial_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_events_source_type'))
        batch_op.drop_index(batch_op.f('ix_financial_events_source_id'))
        batch_op.drop_index('ix_financial_events_source')
        batch_op.drop_index(batch_op.f('ix_financial_events_reference_number'))
        batch_op.drop_index('ix_financial_events_owner_type')
        batch_op.drop_index(batch_op.f('ix_financial_events_owner_id'))
        batch_op.drop_index('ix_financial_events_owner_event_at')
        batch_op.drop_index(batch_op.f('ix_financial_events_item_type'))
        batch_op.drop_index(batch_op.f('ix_financial_events_item_id'))
        batch_op.drop_index(batch_op.f('ix_financial_events_id'))
        batch_op.drop_index(batch_op.f('ix_financial_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_financial_events_event_subtype'))
        batch_op.drop_index(batch_op.f('ix_financial_events_event_at'))
        batch_op.drop_index(batch_op.f('ix_financial_events_customer_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_financial_events_created_at'))

    op.drop_table('financial_events')
    # ### end Alembic commands ###
