"""auto_batch

Revision ID: c61cf028c5b2
Revises: 0017
Create Date: 2026-07-14 17:07:02.765334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c61cf028c5b2'
down_revision: Union[str, Sequence[str], None] = '0017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_purchase_invoice_owner_number', ['owner_id', 'invoice_number'])

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_payment_status'))
        batch_op.create_index(batch_op.f('ix_purchase_orders_id'), ['id'], unique=False)

    with op.batch_alter_table('recipe_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('substitutes_for_ingredient_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_recipe_items_semi_finished_id'))
        batch_op.create_index(batch_op.f('ix_recipe_items_substitutes_for_ingredient_id'), ['substitutes_for_ingredient_id'], unique=False)
        batch_op.create_foreign_key('fk_recipe_items_ingredients_substitutes', 'ingredients', ['substitutes_for_ingredient_id'], ['id'])

    with op.batch_alter_table('recipe_version_ingredient_substitutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_version_ingredient_subs_id'))
        batch_op.create_index(batch_op.f('ix_recipe_version_ingredient_substitutions_id'), ['id'], unique=False)

    with op.batch_alter_table('shift_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_logs_id'), ['id'], unique=False)

    with op.batch_alter_table('shift_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_records_id'), ['id'], unique=False)

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_stock_movements_stock_locations', 'stock_locations', ['location_id'], ['id'])
        batch_op.create_foreign_key('fk_stock_movements_stock_lots', 'stock_lots', ['lot_id'], ['id'])

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_id'), ['id'], unique=False)

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_system_settings_users', 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_id'), ['id'], unique=False)

    with op.batch_alter_table('waste_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waste_records_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waste_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waste_records_id'))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_id'))

    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_system_settings_users', type_='foreignkey')

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_id'))

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_constraint('fk_stock_movements_stock_locations', type_='foreignkey')
        batch_op.drop_constraint('fk_stock_movements_stock_lots', type_='foreignkey')

    with op.batch_alter_table('shift_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_records_id'))

    with op.batch_alter_table('shift_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_logs_id'))

    with op.batch_alter_table('recipe_version_ingredient_substitutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_version_ingredient_substitutions_id'))
        batch_op.create_index(batch_op.f('ix_recipe_version_ingredient_subs_id'), ['id'], unique=False)

    with op.batch_alter_table('recipe_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recipe_items_ingredients_substitutes', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_recipe_items_substitutes_for_ingredient_id'))
        batch_op.create_index(batch_op.f('ix_recipe_items_semi_finished_id'), ['semi_finished_id'], unique=False)
        batch_op.drop_column('substitutes_for_ingredient_id')

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_id'))
        batch_op.create_index(batch_op.f('ix_purchase_orders_payment_status'), ['payment_status'], unique=False)

    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.drop_constraint('uq_purchase_invoice_owner_number', type_='unique')

    # ### end Alembic commands ###
